[
  {
    "cdVehicleType": "MCB",
    "txVehicleTypeDesc": "Microbús",
    "cdVehicleClass": "1",
    "txVehicleClassDesc": "I",
    "qnMaxSeatsSitting": "12",
    "qnMaxStandingPlaces": "14",
    "qnReducedMobilitySeats": "1",
    "nuVehicleLength": "8.0",
    "cdVehicleBrand": "27",
    "txVehicleBrandName": "MERCEDES",
    "cdVehicleModel": "162",
    "txVehicleModelName": "SPRINTER",
    "cdBodyBrand": "30",
    "txBodyBrandName": "MERCEDES",
    "cdBodyModel": "60",
    "txBodyModelName": "EVOBUS-CITY",
    "cdEngineBrand": "16",
    "txEngineBrandName": "MERCEDES",
    "txPropulsionTechDesc": "GAS OIL",
    "cdRampType": "4",
    "txRampTypeDesc": "RAMPA",
    "txWifiDesc": "NO",
    "dtLastUpdated": "2025-05-15T14:32:00.000Z",
    "cdBus": "10049",
    "idCompany": 1660,
    "idBusinessUnit": "106005094",
    "txBusinessUnitDesc": "URBANOS EUSKADI",
    "idVehicleContract": "U32",
    "txVehicleContractDesc": "Urbano de Arrasate",
    "idLicensePlate": "1498HBC",
    "dtLicencePlateRegistration": "2025-05-15T14:32:00.000Z"
  },
  {
    "cdVehicleType": "STD",
    "txVehicleTypeDesc": "Estándar",
    "cdVehicleClass": "1",
    "txVehicleClassDesc": "I",
    "qnMaxSeatsSitting": "53",
    "qnMaxStandingPlaces": "27",
    "qnReducedMobilitySeats": "1",
    "nuVehicleLength": "12.0",
    "cdVehicleBrand": "46",
    "txVehicleBrandName": "VOLVO",
    "cdVehicleModel": "13",
    "txVehicleModelName": "7900 HIBRIDO",
    "cdBodyBrand": "51",
    "txBodyBrandName": "VOLVO",
    "cdBodyModel": "8",
    "txBodyModelName": "7900",
    "cdEngineBrand": "29",
    "txEngineBrandName": "VOLVO",
    "txPropulsionTechDesc": "HIBRIDO",
    "cdRampType": "4",
    "txRampTypeDesc": "RAMPA",
    "txWifiDesc": "No",
    "dtLastUpdated": "2025-05-15T14:32:00.000Z",
    "cdBus": "10054",
    "idCompany": 1060,
    "idBusinessUnit": "106005094",
    "txBusinessUnitDesc": "URBANOS EUSKADI",
    "idVehicleContract": "U32",
    "txVehicleContractDesc": "Urbano de Arrasate",
    "idLicensePlate": "4696HTW",
    "dtLicencePlateRegistration": "2025-05-15T14:32:00.000Z"
  }
]